inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  #Normal is what the auto-indent function of vim uses.
  EnforcedStyle: normal
