# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d3f4375d405a594758ec08535fa0892810b5b553418b114bbff9f36202ac4e6ccaae5067ccfc5b51eab0eb492aebf50bfadef133c12b7ba67d274aa7a41d7d

test:
  secret_key_base: b942149bb54491f6f1e35e28962e69a0568709e141a0a63f6d502f48483e92b2a8952213eadd91c70f7ff55ef5cd26709e7156bd7af1110457403ae9a3fa7761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
